--- 
driver: 
  name: vagrant
platforms: 
#  - 
#    name: generic/rhel7
##  - 
#  name: centos-6
#  - 
#    name: centos-7
  -  name: debian-7
  -  name: debian-8
#  -  name: debian-9
#  - 
#    name: ubuntu-14.04
#  - 
#    name: ubuntu-16.04
provisioner: 
  deprecations_as_errors: true
  name: chef_zero
suites: 
  - 
    attributes: {}
    name: default
    run_list: 
      - "recipe[snmp::default]"
verifier: 
  name: inspec
